theme: minima
title: Open Human Rights Project Violations Database
description: This database is intended to provide visibility into global human rights issues, categorized by the Universal Declaration of Human Rights (UDHR), mapping cases to articles violated.
bluesky_username: ohrproject
github_username: ohrproject
rss: rss
