theme: minima
title: Open Human Rights Project Violations Database
description: For tracking & documenting human rights violations worldwide. Clear, precise, and accessible to all.
bluesky_username: ohrproject
github_username: ohrproject
rss: rss
